name: Gradle CI

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt

      - name: Install ProtoBuf compiler
        run: sudo apt update && sudo apt install -y protobuf-compiler

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
